### PR TITLE
[#678] Add absolute path API.

### LINKED ISSUE #115: Raise an error if onOSName sees unrecognized OS.
I recently saw a test with `@conditionals.onOSName(['linux', 'window'])`.

`window` should have been `windows`; the test was skipped unintentionally.

Make onOSName throw an error if it sees an OS name it does not recognize.

### LINKED ISSUE #677: Disable PAM on macOS
We get these errors on macOS

pam should be completly disabled and we should not support OS accounts on macOS

```
Traceback (most recent call last):
  File "/Users/runner/work/1/s/build-server/lib/python2.7/site-packages/chevah/compat/testing/nose_test_timer.py", line 89, in __call__
    self.__target()
  File "/Users/runner/work/1/s/build-server/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/runner/work/1/s/build-server/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/runner/work/1/s/build-server/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/runner/work/1/s/chevah/server/tests/normal/authentication/test_os.py", line 37, in <module>
    system_users._getPAMAuthenticate()
  File "/Users/runner/work/1/s/build-server/lib/python2.7/site-packages/chevah/compat/unix_users.py", line 416, in _getPAMAuthenticate
    from pam import authenticate as pam_authenticate
  File "/Users/runner/work/1/s/build-server/lib/python2.7/site-packages/pam.py", line 83, in <module>
    LIBPAM = load_library('pam', ['libpam.so', 'libpam.so.0', 'libpam.so.1'])
  File "/Users/runner/work/1/s/build-server/lib/python2.7/site-packages/pam.py", line 46, in load_library
    raise AssertionError("Failed to load '%s' library." % (nickname))
AssertionError: Failed to load 'pam' library.

```

### LINKED ISSUE #678: Add api for absolute path.
Windows can have many absolute path formats, and Python stdlib will not recognize all of them.

For example, it can't recongnize Windows Share paths

```
>>> import ntpath
>>> ntpath.isabs(r'\\bla\tra')
False
>>> ntpath.isabs(r'\not\an\abs')
True
```

MS docs - https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats

image

We need to add a compat API helper.

### PR DESCRIPTION
**Pull request by adiroiban**
Scope
=====

Fixes #678 
Fixes #677 
Fixes #115 

We need a custom API to detect if a path is absolute.

And as part of this PR, we might need to add support for handling windows shares as segments.

Changes
=======

As a drive-by I have updated brink.sh and conf.
Also updated the GitHub actions workflow with latest oses.

How to try and test the changes
===============================

reviewers: @danuker 

check that changes make sense.

### CODE REVIEW

File: brink.sh [hunk 1]
```diff
@@ -732,6 +737,7 @@ detect_os() {
                             check_linux_glibc
                         fi
                         set_os_if_not_generic "ubuntu" $os_version_chevah
+                        set_os_if_not_generic "lnx" ""
```
Comment (adiroiban) [inline brink.sh:740]: this is a hack while we have Ubuntu 22.04 support.

File: chevah/compat/nt_filesystem.py [hunk 2]
```diff
@@ -153,12 +153,6 @@ def getEncodedPath(cls, path):
         lever API for accessing the filesystem.'''
         return path
 
-    def getAbsolutePath(self, path):
```
Comment (adiroiban) [inline chevah/compat/nt_filesystem.py:156]: this was not used.

File: chevah/compat/nt_filesystem.py [hunk 3]
```diff
@@ -264,10 +286,10 @@ def getSegmentsFromRealPath(self, path):
 
         path = text_type(path)
 
-        target = os.path.abspath(path.replace('/', '\\')).lower()
+        target = os.path.normpath(path.replace('/', '\\')).lower()
```
Comment (adiroiban) [inline chevah/compat/nt_filesystem.py:289]: `os.path.abspath` is buggy when the current path is defined as UNC or drive path...so we try to avoid it.

File: chevah/compat/nt_filesystem.py [hunk 4]
```diff
@@ -278,12 +306,12 @@ def getSegmentsFromRealPath(self, path):
 
         head = True
 
-        if path.startswith('\\\\?\\'):
-            # We have a long UNC and we normalize.
+        if path.startswith('\\\\?\\') or path.startswith('\\\\.\\'):
+            # We have a UNC in device path format and we normalize.
```
Comment (danuker) [inline chevah/compat/nt_filesystem.py:310]: Wow! Crazy formats.

**Review by danuker — APPROVED** [review]
I've made a quick look-through, and I am amazed at the amount of path types Windows uses.

Other than that, looks good to me.

**Comment by adiroiban** [comment]
I found a bug with the iterateFolderContent ... which is now fixed

but I need to fix the temp_folder test

needs-changes

**Comment by adiroiban** [comment]
@dumol this is failing due to macos crazy stuff

I don't know what is a valid name... so for compat on latest macOS I have just skipped the tests using OS users.

```
<main> attribute status: eDSRecordAlreadyExists
<dscl_cmd> DS Error: -14135 (eDSRecordAlreadyExists)
<main> attribute status: eDSRecordAlreadyExists
<dscl_cmd> DS Error: -14135 (eDSRecordAlreadyExists)
chgrp: mitZmota: illegal group name
chgrp: gZmatmit: illegal group name
test_temporary_folder_unix - elevated.testing.test_filesystem:TestElevatedLocalTestFilesystem.test_temporary_folder_unix ... ok
test_temporary_folder_nt - elevated.testing.test_filesystem:TestElevatedLocalTestFilesystem.test_temporary_folder_nt ... SKIP: OS family "nt" not available.
SKIP: OS family "nt" not available.
chgrp: gZmatmit: illegal group name
```

**Comment by adiroiban** [comment]
I am going to merge this as it was opened a long time.

If we find any issues, we can open another ticket.

the tests are green and I think the main issue is fixed

**Comment by dumol** [comment]
> @dumol this is failing due to macos crazy stuff
> 
> I don't know what is a valid name... so for compat on latest macOS I have just skipped the tests using OS users.
> 
> ```
> <main> attribute status: eDSRecordAlreadyExists
> <dscl_cmd> DS Error: -14135 (eDSRecordAlreadyExists)
> <main> attribute status: eDSRecordAlreadyExists
> <dscl_cmd> DS Error: -14135 (eDSRecordAlreadyExists)
> chgrp: mitZmota: illegal group name
> chgrp: gZmatmit: illegal group name
> test_temporary_folder_unix - elevated.testing.test_filesystem:TestElevatedLocalTestFilesystem.test_temporary_folder_unix ... ok
> test_temporary_folder_nt - elevated.testing.test_filesystem:TestElevatedLocalTestFilesystem.test_temporary_folder_nt ... SKIP: OS family "nt" not available.
> SKIP: OS family "nt" not available.
> chgrp: gZmatmit: illegal group name
> ```

On macOS, the error _illegal group name_ means the group doesn't exist, according to https://stackoverflow.com/a/33348082/9268255.

**Comment by adiroiban** [comment]
> On macOS, the error illegal group name means the group doesn't exist, according to

Thanks. For now, I will just ignore macos. I hope I will not have to look into this soon.
